/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include "TestUtils.h"

int main()
{
	START_TIMER;
	unsigned int i1 = 1;
	unsigned int i2 = 1;
	unsigned int fib = i1 + i1;
	unsigned int sum = 0;
	while( fib <= 4e6 )
	{
		if( fib % 2 == 0 )
		{
			sum += fib;
		}
		i1 = i2;
		i2 = fib;
		fib += i1;
	}

	return result(4613732, sum);
}
